spring:
  application.name: My Journal
  main.allow-circular-references: true

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.b2m0s9l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_APP_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server.port: 8080

logging.level.com.rushproject.myJournal: DEBUG

weather.api.key: ${WEATHER_API_KEY}